"""restore fk on llm_phrases.job_id

Revision ID: 3ab1cfeae038
Revises: eef7d9376f7c
Create Date: 2026-05-10 05:10:16.215240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab1cfeae038'
down_revision: Union[str, Sequence[str], None] = 'eef7d9376f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'llm_phrases', 'batch_jobs', ['job_id'], ['job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'llm_phrases', type_='foreignkey')
    # ### end Alembic commands ###
