"""drop fk from llm_phrases.job_id

Revision ID: b94ca12a457c
Revises: e86e2712ad10
Create Date: 2026-05-10 04:58:15.108680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94ca12a457c'
down_revision: Union[str, Sequence[str], None] = 'e86e2712ad10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('llm_phrases_job_id_fkey'), 'llm_phrases', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('llm_phrases_job_id_fkey'), 'llm_phrases', 'batch_jobs', ['job_id'], ['job_id'])
    # ### end Alembic commands ###
