"""add movie timestamps

Revision ID: c795bc581b4b
Revises: e49ba9e2e3a0
Create Date: 2026-05-10 01:22:24.363989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c795bc581b4b'
down_revision: Union[str, Sequence[str], None] = 'e49ba9e2e3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'movies',
        sa.Column('registered_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    )
    op.add_column(
        'movies',
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'updated_at')
    op.drop_column('movies', 'registered_at')
    # ### end Alembic commands ###
