"""create initial tables

Revision ID: e49ba9e2e3a0
Revises: 
Create Date: 2026-05-09 23:56:59.751514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e49ba9e2e3a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('movie_id', sa.String(length=50), nullable=False),
    sa.Column('movie_title', sa.String(length=255), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_table('opinion_groups',
    sa.Column('cluster_id', sa.String(length=100), nullable=False),
    sa.Column('movie_id', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=50), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    op.create_index(op.f('ix_opinion_groups_movie_id'), 'opinion_groups', ['movie_id'], unique=False)
    op.create_table('batch_jobs',
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('movie_id', sa.String(length=50), nullable=False),
    sa.Column('movie_title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_batch_jobs_movie_id'), 'batch_jobs', ['movie_id'], unique=False)
    op.create_index(op.f('ix_batch_jobs_status'), 'batch_jobs', ['status'], unique=False)
    op.create_table('movie_summary',
    sa.Column('movie_id', sa.String(length=50), nullable=False),
    sa.Column('positive_percent', sa.Float(), nullable=False),
    sa.Column('negative_percent', sa.Float(), nullable=False),
    sa.Column('positive_review_count', sa.Integer(), nullable=False),
    sa.Column('negative_review_count', sa.Integer(), nullable=False),
    sa.Column('tie_review_count', sa.Integer(), nullable=False),
    sa.Column('total_review_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.String(length=100), nullable=False),
    sa.Column('movie_id', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_reviews_is_processed'), 'reviews', ['is_processed'], unique=False)
    op.create_index(op.f('ix_reviews_movie_id'), 'reviews', ['movie_id'], unique=False)
    op.create_table('llm_phrases',
    sa.Column('phrase_id', sa.String(length=100), nullable=False),
    sa.Column('review_id', sa.String(length=100), nullable=False),
    sa.Column('movie_id', sa.String(length=50), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.review_id'], ),
    sa.PrimaryKeyConstraint('phrase_id')
    )
    op.create_index(op.f('ix_llm_phrases_movie_id'), 'llm_phrases', ['movie_id'], unique=False)
    op.create_index(op.f('ix_llm_phrases_review_id'), 'llm_phrases', ['review_id'], unique=False)
    op.create_table('review_cluster_map',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('cluster_id', sa.String(length=100), nullable=False),
    sa.Column('review_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['opinion_groups.cluster_id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.review_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_cluster_map_cluster_id'), 'review_cluster_map', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_review_cluster_map_review_id'), 'review_cluster_map', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_cluster_map_review_id'), table_name='review_cluster_map')
    op.drop_index(op.f('ix_review_cluster_map_cluster_id'), table_name='review_cluster_map')
    op.drop_table('review_cluster_map')
    op.drop_index(op.f('ix_llm_phrases_review_id'), table_name='llm_phrases')
    op.drop_index(op.f('ix_llm_phrases_movie_id'), table_name='llm_phrases')
    op.drop_table('llm_phrases')
    op.drop_index(op.f('ix_reviews_movie_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_is_processed'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('movie_summary')
    op.drop_index(op.f('ix_batch_jobs_status'), table_name='batch_jobs')
    op.drop_index(op.f('ix_batch_jobs_movie_id'), table_name='batch_jobs')
    op.drop_table('batch_jobs')
    op.drop_index(op.f('ix_opinion_groups_movie_id'), table_name='opinion_groups')
    op.drop_table('opinion_groups')
    op.drop_table('movies')
    # ### end Alembic commands ###
