"""add job_id to llm_phrases

Revision ID: e86e2712ad10
Revises: c795bc581b4b
Create Date: 2026-05-10 04:53:03.070307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86e2712ad10'
down_revision: Union[str, Sequence[str], None] = 'c795bc581b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_phrases', sa.Column('job_id', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_llm_phrases_job_id'), 'llm_phrases', ['job_id'], unique=False)
    op.create_foreign_key(None, 'llm_phrases', 'batch_jobs', ['job_id'], ['job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'llm_phrases', type_='foreignkey')
    op.drop_index(op.f('ix_llm_phrases_job_id'), table_name='llm_phrases')
    op.drop_column('llm_phrases', 'job_id')
    # ### end Alembic commands ###
