"""add target_date started_at finished_at to batch_jobs

Revision ID: eef7d9376f7c
Revises: b94ca12a457c
Create Date: 2026-05-10 05:08:43.680529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef7d9376f7c'
down_revision: Union[str, Sequence[str], None] = 'b94ca12a457c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_jobs', sa.Column('target_date', sa.Date(), nullable=False))
    op.add_column('batch_jobs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('batch_jobs', sa.Column('finished_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batch_jobs', 'finished_at')
    op.drop_column('batch_jobs', 'started_at')
    op.drop_column('batch_jobs', 'target_date')
    # ### end Alembic commands ###
